# -*- coding: utf-8 -*-
"""Reto Miércoles

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IFLZelITONLOLsn0E19kEI64Fyq4cv00
"""

def validar_nombre(nombre):
    return 5 <= len(nombre) <= 50

def validar_apellidos(apellidos):
    return 5 <= len(apellidos) <= 50

def validar_telefono(telefono):
    return len(telefono) == 10 and telefono.isdigit()

def validar_correo(correo):
    return 5 <= len(correo) <= 50 and '@' in correo and '.' in correo

def generar_id(registro_id):
    return registro_id + 1

def imprimir_registros(registros):
    print("\nListado de registros:")
    for registro in registros:
        print(registro)

def registrar_usuario(registros, registro_id):
    nombre = input("Ingrese su nombre: ")
    while not validar_nombre(nombre):
        print("El nombre debe tener entre 5 y 50 caracteres.")
        nombre = input("Ingrese su nombre nuevamente: ")

    apellidos = input("Ingrese sus apellidos: ")
    while not validar_apellidos(apellidos):
        print("Los apellidos deben tener entre 5 y 50 caracteres.")
        apellidos = input("Ingrese sus apellidos nuevamente: ")

    telefono = input("Ingrese su número de teléfono: ")
    while not validar_telefono(telefono):
        print("El número de teléfono debe tener 10 dígitos.")
        telefono = input("Ingrese su número de teléfono nuevamente: ")

    correo = input("Ingrese su correo electrónico: ")
    while not validar_correo(correo):
        print("El correo electrónico debe tener entre 5 y 50 caracteres y ser válido.")
        correo = input("Ingrese su correo electrónico nuevamente: ")

    registro = f"ID: {registro_id}, Nombre: {nombre}, Apellidos: {apellidos}, Teléfono: {telefono}, Correo: {correo}"
    registros.append(registro)
    print("Usuario registrado con éxito!")
    return registros, generar_id(registro_id)

def main():
    registros = []
    registro_id = 0
    try:
        cantidad_usuarios = int(input("¿Cuántos nuevos usuarios desea registrar? "))
        for i in range(cantidad_usuarios):
            print(f"\nRegistrando usuario #{i+1}")
            registros, registro_id = registrar_usuario(registros, registro_id)

        imprimir_registros(registros)
    except ValueError:
        print("Por favor, ingrese un número válido.")

if __name__ == "__main__":
    main()